# Generated by Django 5.1.2 on 2025-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='uploads/listing')),
                ('images1', models.ImageField(blank=True, upload_to='uploads/listing')),
                ('images2', models.ImageField(blank=True, upload_to='uploads/listing')),
                ('images3', models.ImageField(blank=True, upload_to='uploads/listing')),
            ],
        ),
    ]
