# Generated by Django 5.1.2 on 2025-01-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurelisting',
            name='images1',
        ),
        migrations.RemoveField(
            model_name='futurelisting',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='futurelisting',
            name='images3',
        ),
    ]
