# Generated by Django 5.1.2 on 2025-01-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_futurelisting_images1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurelisting',
            old_name='images',
            new_name='image',
        ),
    ]
