# Generated by Django 5.1.2 on 2025-01-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_images_futurelisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurelisting',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
