# Generated by Django 5.1.2 on 2025-01-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_futurelisting_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FutureListing',
        ),
    ]
